modLoader = "kotlinforforge"
loaderVersion = "[3,)"
license = "MIT"

issueTrackerURL = "https://github.com/Talia-12/EmptyHexCastingAddon/issues"

[[mods]]
modId = "yourmod"
version = "${file.jarVersion}"
displayName = "Your Mod"
displayURL = "https://github.com/Talia-12/EmptyHexCastingAddon"
logoFile = "logo.png"
credits = "petrak@ and other developers of Hex Casting for the mod that this is an addon for. Talia for setting up the empty project structure that this is based on."
authors = "You!"
description = ""

[[dependencies.yourmod]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yourmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yourmod]]
modId = "paucal"
mandatory = true
versionRange = "[0.5.0,0.6.0)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yourmod]]
modId = "patchouli"
mandatory = true
versionRange = "[1.19.2-77,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yourmod]]
modId = "hexcasting"
mandatory = true
versionRange = "[0.10.1,)"
ordering = "NONE"
side = "BOTH"
